[build]
  command = "npm run build"  # Adjust as per your project setup
  publish = "dist"           # Adjust the publish directory as needed

[[plugins]]
  package = "@netlify/plugin-image-optimizer"

[[redirects]]
  from = "/old-path/*"
  to = "/new-path/:splat"
  status = 301
  force = true
